export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INBOUND_RATE_LIMIT: 'INBOUND_RATE_LIMIT',
  UPSTREAM_CLIENT_ERROR: 'UPSTREAM_CLIENT_ERROR',
  UPSTREAM_SERVER_ERROR: 'UPSTREAM_SERVER_ERROR',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  UPSTREAM_NETWORK_ERROR: 'UPSTREAM_NETWORK_ERROR',
  UPSTREAM_INVALID_RESPONSE: 'UPSTREAM_INVALID_RESPONSE',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
